name: SonarCloud
run-name: ${{ github.actor }} testing with GitHub Actions
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
  
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: src/main/java/com/ispw/esameispw/
        run: |
          ls ${{ github.workspace }}
      - run: echo " ${{ job.status }}."
